export const condition = {
  NIGHTTIME: '밤에',
  HIGH_FRIENDSHIP: 'high Friendship',
  USE_ICE_STONE: '얼음의돌',
  USE_FIRE_STONE: '불꽃의돌',
  TRADE: 'Trade',
  TRADE_HOLDING_KINGS_ROCK: '왕의징표석을 지니게 한 뒤',
  USE_GALARICA_CUFF: '가라두구팔찌',
  USE_GALARICA_WREATH: '가라두구머리장식',
  ACHIEVE_3_CRITICAL_HITS_IN_ONE_BATTLE: 'achieve 3 critical hits in one battle',
  USE_WATER_STONE: '물의돌',
  TRADE_HOLDING_METAL_COAT: '금속코트를 지니게 한 뒤',
  USE_LEAF_STONE: '리프의돌',
  OUTSIDE_ALOLA: 'outside Alola',
  IN_ALOLA: '알로라 지방에서',
  'ATTACK>DEFENSE': '공격 > 방어일 때',
  'ATTACK<DEFENSE': '공격 < 방어일 때',
  'ATTACK=DEFENSE': '공격 = 방어일 때',
  AFTER_ROLLOUT_LEARNED: 'after Rollout learned',
  IN_GALAR: '가라르 지방에서',
  HOLD_OVAL_STONE: 'hold Oval Stone',
  DAYTIME: '낮에',
  AFTER_ANCIENT_POWER_LEARNED: 'after Ancient Power learned',
  AFTER_MIMIC_LEARNED: 'after Mimic learned',
  USE_THUNDER_STONE: '천둥의돌',
  LEVEL_UP_NEAR_A_MOSSY_ROCK: 'level up near a Mossy Rock',
  LEVEL_UP_NEAR_AN_ICY_ROCK: 'level up near an Icy Rock',
  AFFECTION_IN_POKEMON_AMIE: '♥♥ Affection in Pokémon Amie',
  KNOWING_FAIRY_MOVE: 'knowing Fairy move',
  TRADE_HOLDING_UPGRADE: 'trade holding Upgrade',
  AFTER_DOUBLE_HIT_LEARNED: 'after Double Hit learned',
  USE_SUN_STONE: '태양의돌',
  USE_DUSK_STONE: '어둠의돌',
  HOLD_RAZOR_FANG: 'hold Razor Fang',
  HOLD_RAZOR_CLAW: 'hold Razor Claw',
  WITH_REMORAID_IN_PARTY: 'with Remoraid in party',
  RANDOM_BASED_ON_PERSONALITY: '랜덤',
  EMPTY_SPOT_IN_PARTY: '파티에 빈 공간이 있을 때',
  POKEBALL_IN_BAG: 'Pokéball in bag',
  LEVEL_UP_IN_A_MAGNETIC_FIELD_AREA: 'level up in a Magnetic Field area',
  USE_MOON_STONE: '달의돌',
  TRADE_HOLDING_PRISM_SCALE: 'trade holding Prism Scale',
  OR_LEVEL_UP_WITH_MAX_BEAUTY: 'or level up with max Beauty',
  USE_DAWN_STONE: '각성의돌',
  FEMALE: '암컷일 때',
  TRADE_HOLDING_DEEP_SEA_TOOTH: 'trade holding Deep Sea Tooth',
  TRADE_HOLDING_DEEP_SEA_SCALE: 'trade holding Deep Sea Scale',
  MALE: '수컷일 때',
  IN_GRASS: 'in grass',
  IN_CAVES: 'in caves',
  IN_BUILDINGS: 'in buildings',
  NEAR_DUSTY_BOWL: 'near Dusty Bowl',
  USE_SHINY_STONE: '빛의돌',
  TRADE_WITH_SHELMET: 'Trade with Shelmet',
  TRADE_WITH_KARRABLAST: 'Trade with Karrablast',
  DARK_TYPE_POKEMON_IN_PARTY: '악 타입 포켓몬을 지니고 있을 때',
  TRADE_HOLDING_SACHET: 'trade holding Sachet',
  TRADE_HOLDING_WHIPPED_DREAM: 'trade holding Whipped Dream',
  HOLDING_CONSOLE_UPSIDEDOWN: '닌텐도 스위치 본체/컨트롤러의 위아래를 뒤집었을 때',
  AT_MOUNT_LANAKILA: 'at Mount Lanakila',
  IN_POKEMON_SUN_OR_ULTRA_SUN: '썬, 울트라썬, 소드 버전에서',
  IN_POKEMON_MOON_OR_ULTRA_MOON: '문, 울트라문, 실드 버전에서',
  'DUSK_5-6PM': 'Dusk 5-6pm',
  'IN_ULTRA_SUN/MOON': 'in Ultra Sun/Moon',
  AFTER_DRAGON_PULSE_LEARNED: 'after Dragon Pulse learned',
  POKEMON_GO_ONLY: 'Pokémon GO only',
  '400_MELTAN_CANDIES': '400 Meltan Candies',
  USE_TART_APPLE: '새콤한 사과',
  USE_SWEET_APPLE: '달콤한 사과',
  WITH_A_LOW_KEY_NATURE:
    '노력, 고집, 개구쟁이, 용감, 온순, 장난꾸러기, 촐랑, 덜렁, 변덕, 건방, 성급, 명랑, 천진난만 성격일 때',
  WITH_AN_AMPED_NATURE: '외로움, 대담, 무사태평, 조심, 의젓, 수줍음, 냉정, 차분, 얌전, 신중, 겁쟁이, 성실 성격일 때',
  AFTER_TAUNT_LEARNED: 'after Taunt learned',
  USE_CRACKED_POT: '깨진 포트 or 이빠진 포트',
  SPIN_AROUND_HOLDING_SWEET: 'spin around holding Sweet',
  IN_TOWER_OF_DARKNESS: 'in Tower of Darkness',
  IN_TOWER_OF_WATER: 'in Tower of Water',
};
