export const DIFFERENT_FORM = {
  MEGA_X: '메가진화 X',
  MEGA_Y: '메가진화 Y',
  MEGA: '메가진화',
  GALARIAN_STANDARD_MODE: '리전 폼',
  GALARIAN_ZEN_MODE: '리전 폼 달마모드',
  ALOLA: '알로라 폼',
  GALAR: '가라르 폼',
  SUNNY_FORM: '태양의 모습',
  RAINY_FORM: '빗방울의 모습',
  SNOWY_FORM: '설운의 모습',
  PRIMAL: '원시회귀',
  NORMAL_FORM: '노말 폼',
  ATTACK_FORM: '어택 폼',
  DEFENSE_FORM: '디펜스 폼',
  SPEED_FORM: '스피드 폼',
  PLANT_CLOAK: '초목도롱',
  SANDY_CLOAK: '모래땅도롱',
  TRASH_CLOAK: '슈레도롱',
  HEAT_ROTOM: '히트로토무',
  WASH_ROTOM: '워시로토무',
  FROST_ROTOM: '프로스트로토무',
  FAN_ROTOM: '스핀로토무',
  MOW_ROTOM: '커트로토무',
  ALTERED_FORM: '어나더 폼',
  ORIGIN_FORM: '오리진 폼',
  LAND_FORM: '랜드 폼',
  SKY_FORM: '스카이 폼',
  STANDARD_MODE: '노말 폼',
  ZEN_MODE: '달마모드',
  INCARNATE_FORM: '화신 폼',
  THERIAN_FORM: '영물 폼',
  BLACK_KYUREM: '블랙큐레무',
  WHITE_KYUREM: '화이트큐레무',
  ORDINARY_FORM: '평소의모습',
  RESOLUTE_FORM: '각오의모습',
  ARIA_FORM: '보이스 폼',
  PIROUETTE_FORM: '스텝 폼',
  ASH_GRENINJA: '지우개굴닌자',
  SHIELD_FORM: '실드 폼',
  BLADE_FORM: '블레이드 폼',
  AVERAGE_SIZE: '일반 크기',
  SMALL_SIZE: '작은 크기',
  LARGE_SIZE: '큰 크기',
  SUPER_SIZE: '아주 큰 크기',
  FIFTY_PERCENT_FORM: '50% 폼',
  TEN_PERCENT_FORM: '10% 폼',
  COMPLETE_FORM: '퍼펙트 폼',
  HOOPA_CONFINED: '굴레에 빠진 후파',
  HOOPA_UNBOUND: '굴레를 벗어난 후파',
  BAILE_STYLE: '이글이글 스타일',
  POM_POM_STYLE: '파칙파칙 스타일',
  PA_U_STYLE: '훌라훌라 스타일',
  SENSU_STYLE: '하늘하늘 스타일',
  MIDDAY_FORM: '한낮의 모습',
  MIDNIGHT_FORM: '한밤중의 모습',
  DUSK_FORM: '황혼의 모습',
  SOLO_FORM: '단독의 모습',
  SCHOOL_FORM: '군집의 모습',
  METEOR_FORM: '유성의 모습',
  CORE_FORM: '코어의 모습',
  DUSK_MANE_NECROZMA: '황혼의 갈기',
  DAWN_WINGS_NECROZMA: '새벽의 날개',
  ULTRA_NECROZMA: '울트라네크로즈마',
  LOW_KEY_FORM: '로우한 모습',
  AMPED_FORM: '하이한 모습',
  ICE_FACE: '아이스 페이스',
  NOICE_FACE: '노아이스 페이스',
  FULL_BELLY_MODE: '배부른 모습',
  HUNGRY_MODE: '배고픈 모습',
  HERO_OF_MANY_BATTLES: '역전의 용사',
  CROWNED_SWORD: '검왕',
  CROWNED_SHIELD: '방패왕',
  ETERNAMAX: '무한다이맥스',
  SINGLE_STRIKE_STYLE: '일격의 태세',
  RAPID_STRIKE_STYLE: '연격의 태세',
} as const;
export type DIFFERENT_FORM = typeof DIFFERENT_FORM[keyof typeof DIFFERENT_FORM];

export const EVOLUTION_TYPE = {
  LEVEL: 'level',
  STONE: 'stone',
  TRADE: 'trade',
  FRIENDSHIP: 'friendship',
  STATUS: 'status',
  NONE: 'none',
} as const;
export type EVOLUTION_TYPE = typeof EVOLUTION_TYPE[keyof typeof EVOLUTION_TYPE];

export const ELEMENTAL_STONE = {
  FIRE: '불꽃의돌 사용',
  WATER: '물의돌 사용',
  THUNDER: '천둥의돌 사용',
  LEAF: '리프의돌 사용',
  MOON: '달의돌 사용',
  SUN: '태양의돌 사용',
  SHINY: '빛의돌 사용',
  DUSK: '어둠의돌 사용',
  DAWN: '각성의돌 사용',
  ICE: '얼음의돌 사용',
  TART_APPLE: '새콤한 사과 사용',
  SWEET_APPLE: '달콤한 사과 사용',
  CRACKED_POT: '깨진 포트 or 이빠진 포트 사용',
} as const;
export type ELEMENTAL_STONE = typeof ELEMENTAL_STONE[keyof typeof ELEMENTAL_STONE];

export const LEVEL_CONDITION = {
  NIGHT: '밤에 레벨업',
  DAY: '낮에 레벨업',
  MALE: '수컷일 때 레벨업',
  FEMALE: '암컷일 때 레벨업',
  IN_ALOLA: '알로라지방에서 레벨업',
  IN_GALAR: '가라르지방에서 레벨업',
  HIGH_ATTACK: '공격 > 방어일 때 레벨업',
  LOW_ATTACK: '공격 < 방어일 때 레벨업',
  SAME_ATTACK: '공격 = 방어일 때 레벨업',
  RANDOM: '랜덤',
  EMPTY_PARTY: '파티에 빈 공간이 있을 때 레벨업',
} as const;
export type LEVEL_CONDITION = typeof LEVEL_CONDITION[keyof typeof LEVEL_CONDITION];

export const TRADING_CONDITION = {
  NONE: '통신교환',
  KINGS_ROCK: '왕의징표석을 지니게 한 뒤 통신교환',
  METAL_COAT: '금속코트를 지니게 한 뒤 통신교환',
  PROTECTOR: '프로텍터를 지니게 한 뒤 통신교환',
  DRAGON_SCALE: '용의비늘을 지니게 한 뒤 통신교환',
  ELECTIRIZER: '에레키부스터를 지니게 한 뒤 통신교환',
  MAGMARIZER: '마그마부스터를 지니게 한 뒤 통신교환',
  UPGRADE: '업그레이드를 지니게 한 뒤 통신교환',
  DUBIOUS_DISC: '괴상한패치를 지니게 한 뒤 통신교환',
  PRISM_SCALE: '고운비늘을 지니게 한 뒤 통신교환 또는 아름다움 컨디션이 170 이상일 때 레벨업',
  REAPER_CLOTH: '영계의천을 지니게 한 뒤 통신교환',
  DEEP_SEA_TOOTH: '심해의이빨을 지니게 한 뒤 통신교환',
  DEEP_SEA_SCALE: '심해의비늘을 지니게 한 뒤 통신교환',
  WITH_SHELMET: '쪼마리와 통신교환',
  WITH_KARRABLAST: '딱정곤과 통신교환',
  SACHET: '향기주머니를 지니게 한 뒤 통신교환',
  WHIPPED_DREAM: '휘핑팝을 지니게 한 뒤 통신교환',
} as const;
export type TRADING_CONDITION = typeof TRADING_CONDITION[keyof typeof TRADING_CONDITION];

export const FRIENDSHIP = {
  ...LEVEL_CONDITION,
  NONE: '친밀도가 220 이상일때',
} as const;
export type FRIENDSHIP = typeof FRIENDSHIP[keyof typeof FRIENDSHIP];

const ABILITY_CONDITION = {
  ROLLOUT: '구르기를 배운뒤 레벨업',
  ANCIENT_POWER: '원시의힘을 배운 뒤 레벨업',
  MIMIC: '흉내내기를 배운 뒤 레벨업',
  DOUBLE_HIT: '더블어택을 배운 뒤 레벨업',
  STOMP: '짓밝기를 배운 뒤 레벨업',
  DRAGON_PULSE: '용의파동을 배운 뒤 레벨업',
  TAUNT: '도발을 배운 뒤 레벨업',
} as const;
type ABILITY_CONDITION = typeof ABILITY_CONDITION[keyof typeof ABILITY_CONDITION];
const ITEM_CONDITION = {
  OVAL_STONE: '둥글둥글 돌을 지니게 한 뒤 낮에 레벨업',
  RAZOR_FANG: '예리한이빨을 지니게 한 뒤 밤에 레벨업',
  RAZOR_CLAW: '예리한손톱을 지니게 한 뒤 밤에 레벨업',
  SWEET: '사탕공예를 지니게 하고 L스틱으로 캐릭터를 회전시킨다',
} as const;
type ITEM_CONDITION = typeof ITEM_CONDITION[keyof typeof ITEM_CONDITION];
const AREA_CONDITION = {
  IN_SUN_OR_ULTRA_SUN: '포켓몬스터 썬·울트라썬에서',
  IN_MOON_OR_ULTRA_MOON: '포켓몬스터 문·울트라문에서',
  IN_ULTRA_SUN_OR_ULTRA_MOON: '포켓몬스터 울트라썬·울트라문에서',
  MOSSY_ROCK: '4세대-7세대: 이끼 바위 근처에서 레벨 업, 8세대: 리프의돌 사용',
  ICY_ROCK: '4세대-7세대: 얼음 바위 근처에서 레벨 업, 8세대: 얼음의돌 사용',
} as const;
type AREA_CONDITION = typeof AREA_CONDITION[keyof typeof AREA_CONDITION];
export const OTHER_CONDITION = {
  ...LEVEL_CONDITION,
  ...ABILITY_CONDITION,
  ...ITEM_CONDITION,
  ...AREA_CONDITION,
  LEVEL_UP_IN_A_MAGNETIC_FIELD:
    '천관산(DPPt), 전기돌동굴(BW/BW2), 13번 도로-발전소가 있는 곳(XY), 뉴보라(ORAS), 포니대협곡(SM/USUM), 화끈산(USUM)에서 레벨업',
  RAIN: '비오는 날씨일때 레벨업',
  RANDOM: '랜덤',
  DUSK: '특성이 마이페이스이고 황혼 5시~6시일 때 레벨업',
  PRISM_SCALE: '고운비늘을 지니게 한 뒤 통신교환 또는 아름다움 컨디션이 170 이상일 때 레벨업',
  LOW_KEY: '성격이 노력, 고집, 개구쟁이, 용감, 온순, 장난꾸러기, 촐랑, 덜렁, 변덕, 건방, 성급, 명랑, 천진난만일 때',
  AMPED: '성격이 외로움, 대담, 무사태평, 조심, 의젓, 수줍음, 냉정, 차분, 얌전, 신중, 겁쟁이일 때',
  AFFECTION:
    '6세대-7세대: 포켓파를레를 통해 절친도를 2 이상 올리고 페어리 타입 기술을 배운 뒤 레벨 업, 8세대: 친밀도가 220 이상일 때 페어리 타입 기술을 배운 뒤 레벨 업',
  WITH_REMORAID_IN_PARTY: '총어를 데리고 있는 상태에서 레벨업',
  NEAR_DUSTY_BOWL: '49 이상의 누적 대미지를 입은 후 와일드에리어 모래먼지구덩이에 존재하는 고인돌 아래를 지나감',
  POKEMON_GO: '포켓몬 GO에서 사탕 400개를 이용해 진화',
  CRITICAL_HITS: '한 배틀에서 상대의 급소를 3번 맞춘다',
  IN_TOWER_OF_DARKNESS: '악의탑 제패',
  IN_TOWER_OF_WATER: '물의탑 제패',
} as const;
export type OTHER_CONDITION = typeof OTHER_CONDITION[keyof typeof OTHER_CONDITION];

export const ADDITIONAL_CONDITION = {
  NIGHT: '밤일 때',
  DAY: '낮일 때',
  MALE: '수컷일 때',
  FEMALE: '암컷일 때',
  IN_ALOLA: '알로라지방에서',
  IN_GALAR: '가라르지방에서',
  IN_GRASS: '풀숲에서',
  IN_CAVES: '동굴•사막•해안가에서',
  IN_BUILDINGS: '건물에서',
  OR_LEVEL_UP_IN_A_MAGNETIC_FIELD: '포니대협곡(SM/USUM), 화끈산(USUM)에서 레벨 업',
  ...AREA_CONDITION,
} as const;
export type ADDITIONAL_CONDITION = typeof ADDITIONAL_CONDITION[keyof typeof ADDITIONAL_CONDITION];

export const EXCEPTIONAL_FORM_KEY = {
  MEGA_X: 'MEGA_X',
  MEGA_Y: 'MEGA_Y',
  GALARIAN_STANDARD_MODE: 'GALARIAN_STANDARD_MODE',
  GALARIAN_ZEN_MODE: 'GALARIAN_ZEN_MODE',
  ASH_GRENINJA: 'ASH_GRENINJA',
  FIFTY_PERCENT: 'FIFTY_PERCENT',
  TEN_PERCENT: 'TEN_PERCENT',
  PA_U_STYLE: 'PA_U_STYLE',
  POM_POM_STYLE: 'POM_POM_STYLE',
  HUNGRY_MODE: 'HUNGRY_MODE',
} as const;
export type EXCEPTIONAL_FORM_KEY = typeof EXCEPTIONAL_FORM_KEY[keyof typeof EXCEPTIONAL_FORM_KEY];

export const POKEMON_TYPE = {
  NORMAL: '노말',
  FIRE: '불',
  WATER: '물',
  ELECTRIC: '전기',
  GRASS: '풀',
  ICE: '얼음',
  FIGHTING: '비행',
  POISON: '독',
  GROUND: '땅',
  FLYING: '비행',
  PSYCHIC: '에스퍼',
  BUG: '벌레',
  ROCK: '바위',
  GHOST: '고스트',
  DRAGON: '드래곤',
  DARK: '악',
  STEEL: '강철',
  FAIRY: '페어리',
} as const;
export type POKEMON_TYPE = typeof POKEMON_TYPE[keyof typeof POKEMON_TYPE];

export type Condition =
  | typeof LEVEL_CONDITION
  | typeof ELEMENTAL_STONE
  | typeof TRADING_CONDITION
  | typeof ADDITIONAL_CONDITION;

export const STAT = {
  HP: 'HP',
  ATTACK: '공격',
  DEFENSE: '방어',
  SP_ATTACK: '특수공격',
  SP_DEFENSE: '특수방어',
  SPEED: '스피드',
  TOTAL: '총합',
} as const;
export type STAT = typeof STAT[keyof typeof STAT];

export const ABILITY = {
  STENCH: '악취',
  DRIZZLE: '잔비',
  SPEED_BOOST: '가속',
  BATTLE_ARMOR: '전투무장',
  STURDY: '옹골참',
  DAMP: '습기',
  LIMBER: '유연',
  SAND_VEIL: '모래숨기',
  STATIC: '정전기',
  VOLT_ABSORB: '축전',
  WATER_ABSORB: '저수',
  OBLIVIOUS: '둔감',
  CLOUD_NINE: '날씨부정',
  COMPOUND_EYES: '복안',
  INSOMNIA: '불면',
  COLOR_CHANGE: '변색',
  IMMUNITY: '면역',
  FLASH_FIRE: '타오르는불꽃',
  SHIELD_DUST: '인분',
  OWN_TEMPO: '마이페이스',
  SUCTION_CUPS: '흡반',
  INTIMIDATE: '위협',
  SHADOW_TAG: '그림자밟기',
  ROUGH_SKIN: '까칠한피부',
  WONDER_GUARD: '불가사의부적',
  LEVITATE: '부유',
  EFFECT_SPORE: '포자',
  SYNCHRONIZE: '싱크로',
  CLEAR_BODY: '클리어바디',
  NATURAL_CURE: '자연회복',
  LIGHTNING_ROD: '피뢰침',
  SERENE_GRACE: '하늘의은총',
  SWIFT_SWIM: '쓱쓱',
  CHLOROPHYLL: '엽록소',
  ILLUMINATE: '발광',
  TRACE: '트레이스',
  HUGE_POWER: '천하장사',
  POISON_POINT: '독가시',
  INNER_FOCUS: '정신력',
  MAGMA_ARMOR: '마그마의무장',
  WATER_VEIL: '수의베일',
  MAGNET_PULL: '자력',
  SOUNDPROOF: '방음',
  RAIN_DISH: '젖은접시',
  SAND_STREAM: '모래날림',
  PRESSURE: '프레셔',
  THICK_FAT: '두꺼운지방',
  EARLY_BIRD: '일찍기상',
  FLAME_BODY: '불꽃몸',
  RUN_AWAY: '도주',
  KEEN_EYE: '날카로운눈',
  HYPER_CUTTER: '괴력집게',
  PICKUP: '픽업',
  TRUANT: '게으름',
  HUSTLE: '의욕',
  CUTE_CHARM: '헤롱헤롱바디',
  PLUS: '플러스',
  MINUS: '마이너스',
  FORECAST: '기분파',
  STICKY_HOLD: '점착',
  SHED_SKIN: '탈피',
  GUTS: '근성',
  MARVEL_SCALE: '이상한비늘',
  LIQUID_OOZE: '해감액',
  OVERGROW: '심록',
  BLAZE: '맹화',
  TORRENT: '급류',
  SWARM: '벌레의알림',
  ROCK_HEAD: '돌머리',
  DROUGHT: '가뭄',
  ARENA_TRAP: '개미지옥',
  VITAL_SPIRIT: '의기양양',
  WHITE_SMOKE: '하얀연기',
  PURE_POWER: '순수한힘',
  SHELL_ARMOR: '조가비갑옷',
  AIR_LOCK: '에어록',
  TANGLED_FEET: '갈지자걸음',
  MOTOR_DRIVE: '전기엔진',
  RIVALRY: '투쟁심',
  STEADFAST: '불굴의마음',
  SNOW_CLOAK: '눈숨기',
  GLUTTONY: '먹보',
  ANGER_POINT: '분노의경혈',
  UNBURDEN: '곡예',
  HEATPROOF: '내열',
  SIMPLE: '단순',
  DRY_SKIN: '건조피부',
  DOWNLOAD: '다운로드',
  IRON_FIST: '철주먹',
  POISON_HEAL: '포이즌힐',
  ADAPTABILITY: '적응력',
  SKILL_LINK: '스킬링크',
  HYDRATION: '촉촉바디',
  SOLAR_POWER: '선파워',
  QUICK_FEET: '속보',
  NORMALIZE: '노말스킨',
  SNIPER: '스나이퍼',
  MAGIC_GUARD: '매직가드',
  NO_GUARD: '노가드',
  STALL: '시간벌기',
  TECHNICIAN: '테크니션',
  LEAF_GUARD: '리프가드',
  KLUTZ: '서투름',
  MOLD_BREAKER: '틀깨기',
  SUPER_LUCK: '대운',
  AFTERMATH: '유폭',
  ANTICIPATION: '위험예지',
  FOREWARN: '예지몽',
  UNAWARE: '천진',
  TINTED_LENS: '색안경',
  FILTER: '필터',
  SLOW_START: '슬로스타트',
  SCRAPPY: '배짱',
  STORM_DRAIN: '마중물',
  ICE_BODY: '아이스바디',
  SOLID_ROCK: '하드록',
  SNOW_WARNING: '눈퍼뜨리기',
  HONEY_GATHER: '꿀모으기',
  FRISK: '통찰',
  RECKLESS: '이판사판',
  MULTITYPE: '멀티타입',
  FLOWER_GIFT: '플라워기프트',
  BAD_DREAMS: '나이트메어',
  PICKPOCKET: '나쁜손버릇',
  SHEER_FORCE: '우격다짐',
  CONTRARY: '심술꾸러기',
  UNNERVE: '긴장감',
  DEFIANT: '오기',
  DEFEATIST: '무기력',
  CURSED_BODY: '저주받은바디',
  HEALER: '치유의마음',
  FRIEND_GUARD: '프렌드가드',
  WEAK_ARMOR: '깨어진갑옷',
  HEAVY_METAL: '헤비메탈',
  LIGHT_METAL: '라이트메탈',
  MULTISCALE: '멀티스케일',
  TOXIC_BOOST: '독폭주',
  FLARE_BOOST: '열폭주',
  HARVEST: '수확',
  TELEPATHY: '텔레파시',
  MOODY: '변덕쟁이',
  OVERCOAT: '방진',
  POISON_TOUCH: '독수',
  REGENERATOR: '재생력',
  BIG_PECKS: '부풀린가슴',
  SAND_RUSH: '모래헤치기',
  WONDER_SKIN: '미라클스킨',
  ANALYTIC: '애널라이즈',
  ILLUSION: '일루전',
  IMPOSTER: '괴짜',
  INFILTRATOR: '틈새포착',
  MUMMY: '미라',
  MOXIE: '자기과신',
  JUSTIFIED: '정의의마음',
  RATTLED: '주눅',
  MAGIC_BOUNCE: '매직미러',
  SAP_SIPPER: '초식',
  PRANKSTER: '짓궂은마음',
  SAND_FORCE: '모래의힘',
  IRON_BARBS: '철가시',
  ZEN_MODE: '달마모드',
  VICTORY_STAR: '승리의별',
  TURBOBLAZE: '터보블레이즈',
  TERAVOLT: '테라볼티지',
  AROMA_VEIL: '아로마베일',
  FLOWER_VEIL: '플라워베일',
  CHEEK_POUCH: '볼주머니',
  PROTEAN: '변환자재',
  FUR_COAT: '퍼코트',
  MAGICIAN: '매지션',
  BULLETPROOF: '방탄',
  COMPETITIVE: '승기',
  STRONG_JAW: '옹골찬턱',
  REFRIGERATE: '프리즈스킨',
  SWEET_VEIL: '스위트베일',
  STANCE_CHANGE: '배틀스위치',
  GALE_WINGS: '질풍날개',
  MEGA_LAUNCHER: '메가런처',
  GRASS_PELT: '풀모피',
  SYMBIOSIS: '공생',
  TOUGH_CLAWS: '단단한발톱',
  PIXILATE: '페어리스킨',
  GOOEY: '미끈미끈',
  AERILATE: '스카이스킨',
  PARENTAL_BOND: '부자유친',
  DARK_AURA: '다크오라',
  FAIRY_AURA: '페어리오라',
  AURA_BREAK: '오라브레이크',
  PRIMORDIAL_SEA: '시작의바다',
  DESOLATE_LAND: '끝의대지',
  DELTA_STREAM: '델타스트림',
  RKS_SYSTEM: 'AR시스템',
  LIQUID_VOICE: '촉촉보이스',
  GALVANIZE: '일렉트릭스킨',
  LONG_REACH: '원격',
  DANCER: '무희',
  TANGLING_HAIR: '컬리헤어',
  POWER_OF_ALCHEMY: '과학의힘',
  EMERGENCY_EXIT: '위기회피',
  BERSERK: '발끈',
  SCHOOLING: '어군',
  SURGE_SURFER: '서핑테일',
  STAMINA: '지구력',
  QUEENLY_MAJESTY: '여왕의위엄',
  WATER_BUBBLE: '수포',
  POWER_CONSTRUCT: '스웜체인지',
  COMATOSE: '절대안깸',
  INNARDS_OUT: '내용물분출',
  WIMP_OUT: '도망태세',
  STEELWORKER: '강철술사',
  DISGUISE: '탈',
  BATTERY: '배터리',
  STAKEOUT: '잠복',
  TRIAGE: '힐링시프트',
  MERCILESS: '무도한행동',
  DAZZLING: '비비드바디',
  CORROSION: '부식',
  WATER_COMPACTION: '꾸덕꾸덕굳기',
  FLUFFY: '복슬복슬',
  SLUSH_RUSH: '눈치우기',
  SHIELDS_DOWN: '리밋실드',
  RECEIVER: '리시버',
  ELECTRIC_SURGE: '일렉트릭메이커',
  PSYCHIC_SURGE: '사이코메이커',
  GRASSY_SURGE: '그래스메이커',
  MISTY_SURGE: '미스트메이커',
  FULL_METAL_BODY: '메탈프로텍트',
  SHADOW_SHIELD: '스펙터가드',
  BEAST_BOOST: '비스트부스트',
  PRISM_ARMOR: '프리즘아머',
  SOUL_HEART: '소울하트',
  STEELY_SPIRIT: '강철정신',
  STALWART: '굳건한신념',
  GULP_MISSILE: '그대로꿀꺽미사일',
  HUNGER_SWITCH: '꼬르륵스위치',
  WANDERING_SPIRIT: '떠도는영혼',
  LIBERO: '리베로',
  PERISH_BODY: '멸망의바디',
  SAND_SPIT: '모래뿜기',
  GORILLA_TACTICS: '무아지경',
  MIRROR_ARMOR: '미러아머',
  SCREEN_CLEANER: '배리어프리',
  UNSEEN_FIST: '보이지않는주먹',
  BALL_FETCH: '볼줍기',
  DAUNTLESS_SHIELD: '불굴의방패',
  INTREPID_SWORD: '불요의검',
  COTTON_DOWN: '솜털',
  RIPEN: '숙성',
  PROPELLER_TAIL: '스크루지느러미',
  ICE_FACE: '아이스페이스',
  ICE_SCALES: '얼음인분',
  DRAGON_S_MAW: '용의턱',
  MIMICRY: '의태',
  STEAM_ENGINE: '증기기관',
  QUICK_DRAW: '퀵드로',
  TRANSISTOR: '트랜지스터',
  PASTEL_VEIL: '파스텔베일',
  POWER_SPOT: '파워스폿',
  PUNK_ROCK: '펑크록',
  NEUTRALIZING_GAS: '화학변화가스',
} as const;
export type ABILITY = typeof ABILITY[keyof typeof ABILITY];
